### ISSUE TITLE
Searching for a term inside the gene search set results does not seem to work

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/rummagene#62]
Run this query and tried narrowing it down by search for "prion" https://rummagene.com/enrich?dataset=ebc33ac6-0d1f-4c63-9380-2f7e19db4b78

https://rummagene.com/enrich?dataset=ebc33ac6-0d1f-4c63-9380-2f7e19db4b78&page=4&q=prion

https://github.com/user-attachments/assets/6156dea6-e88e-4134-9fb3-041103247c50

**Comment by u8sand** [comment]
So this isn't in the term of the gene set -- it's in the paper's title, that's why it doesn't show up.
